export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const HIDDEN = 'HIDDEN';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const GET_COLLECTION_DATA_SUCCESS = 'GET_COLLECTION_DATA_SUCCESS';
export const LOADING_DATA = 'LOADING_DATA';
export const GET_COLLECTION_DATA_FAILED = 'GET_COLLECTION_DATA_FAILED';
